---
exclude_paths:
  - 'WeeklyBlogTemplate/Properties/*'
  - 'WeeklyBlogTemplate/Settings.cs'
  - 'WeeklyBlogTemplateTests/*'
  - 'WeeklyBlogTemplateTests/Common/*'
  - 'WeeklyBlogTemplateTests/Properties/*'
